StarSpaceWeb/StarSpaceWeb/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.Index.as_view(), name='home'),
    path('accounts/',include('accounts.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('posts/',include('posts.urls')),
    path('groups/',include('groups.urls')),
]

StarSpaceWeb/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('create', views.CreatePost.as_view(), name='create'),
    path('by/<slug:username>', views.UserPosts.as_view(), name='for_user'),
    path('by/<slug:username>/<slug:pk>', views.PostDetail.as_view(), name='single'),
    path('create/comment', views.CreateComment.as_view(), name='create_comment')
]

StarSpaceWeb/posts/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings

from groups.models import Group

from django.contrib.auth import get_user_model
User = get_user_model()

class Post(models.Model):
    user = models.ForeignKey(User, related_name='posts', on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now=True)
    title = models.CharField(max_length=30)
    message = models.TextField()
    # message_html = models.TextField(editable = False)
    group = models.ForeignKey(Group, related_name='posts', null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        # self.message_html = misika.html(self.message)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('posts:single', kwargs={'username':self.user.username, 'pk':self.pk} )

    class Meta:
        ordering = ['-created_date']
        unique_together = ['user','message']

class Comments(models.Model):
    user = models.ForeignKey(User, related_name='comments_all', on_delete=models.CASCADE)
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now=True)
    message = models.TextField()
    def __str__(self):
        return self.message

    def save(self, *args, **kwargs):
        # self.message_html = misika.html(self.message)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('posts:single', kwargs={'username':self.post.user.username, 'pk':self.post.pk} )

    class Meta:
        ordering = ['-created_date']
        unique_together = ['user','message']

StarSpaceWeb/posts/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from django.views import generic
from django.http import Http404
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages

from braces.views import SelectRelatedMixin
from . import models
from . import forms

from django.contrib.auth import get_user_model
User = get_user_model()

class UserPosts(generic.ListView):
    model = models.Post
    template_name = "user_post_list.html"

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related("posts").get(
                username__iexact=self.kwargs.get("username")
            )
        except ObjectDoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post_user"] = self.post_user
        return context


class PostDetail(generic.DetailView):
    model = models.Post
    select_related = ['user', 'group']
    template_name = 'post_detail.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact = self.kwargs.get('username'))

class CreatePost(generic.CreateView, SelectRelatedMixin, LoginRequiredMixin):
    model = models.Post
    fields = ['title', 'message', 'group']
    template_name = 'post_form.html'

    def form_valid(self, form):
        self.object = form.save(commit = False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class CreateComment (generic.CreateView, SelectRelatedMixin, LoginRequiredMixin):
    model = models.Comments
    fields = ['message', 'post']
    template_name = 'comments_form.html'

    def form_valid(self, form):
        self.object = form.save(commit = False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

    def get_absolute_url(self):
        return reverse('posts:single', kwargs={'username':self.post_user.username, 'pk':self.post} )

StarSpaceWeb/posts/templates/_post.html
<br>
<a href="{% url 'posts:for_user' username=post.user.username %}"> <strong>@{{post.user.username}}</strong> </a> {{post.title}}
<a href="{% url 'posts:single' username=post.user.username pk=post.pk %}">open</a>
<br>

StarSpaceWeb/posts/templates/comments_form.html
{% extends 'post_base.html' %}

{% block post_content %}
    <h4>Create a new coment:</h4>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Done" class="btn btn-md btn-black-outline display-4">
    </form>
{% endblock %}

StarSpaceWeb/posts/templates/post_base.html
{% extends 'base.html' %}

{% block content %}
<section class="header1 cid-s1BGr2B907" id="header16-19">
    <div class="container">
        <div class="row justify-content-md-left">
            <div class="col-md-10 align-left">
                {% block pre_post %} {% endblock %}
                {% block post_content %} {% endblock %}
                {% block post_post %} {% endblock %}
            </div>
        </div>
    </div>

</section>
{% endblock %}

StarSpaceWeb/posts/templates/post_detail.html
{% extends 'post_base.html' %}

{% block post_content %}
    <h2>{{ post.title }}</h2>
    <a href="{% url 'posts:for_user' username=post.user.username %}"> <strong>@{{post.user.username}}</strong> </a>
    <br> <p>{{post.message}}</p>

    <a href="{% url 'posts:create_comment' %}">add comment </a>
    <h5>Comments: {{ post.comments.count }}</h5>
    {% for c in post.comments.all %}
        <a href="{% url 'posts:for_user' username=c.user.username %}"> <strong>@{{c.user.username}}</strong> </a>
        <p>{{c.message}}</p>
    {% endfor %}

{% endblock %}

StarSpaceWeb/posts/templates/post_form.html
{% extends 'post_base.html' %}

{% block post_content %}
    <h4>Create a new post:</h4>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Post" class="btn btn-md btn-black-outline display-4">
    </form>
{% endblock %}

StarSpaceWeb/posts/templates/user_post_list.html
{% extends 'post_base.html' %}

{% block pre_post %}
    <h2>@{{post_user.username}}</h2>
{% endblock %}

{% block post_content %}
    {% if not post_list %}
        <p>No post yet</p>
    {% else %}
        {% for p in post_list %}
            <br>
            <a href="{% url 'posts:for_user' username=p.user.username %}"> <strong>@{{p.user.username}}</strong> </a> {{p.title}}
            <a href="{% url 'posts:single' username=p.user.username pk=p.pk %}">open</a>
            <br>
        {% endfor %}
    {% endif %}
{% endblock %}