StarSpaceWeb/StarSpaceWeb/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.Index.as_view(), name='home'),
    path('accounts/',include('accounts.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('posts/',include('posts.urls')),
    path('groups/',include('groups.urls')),
]

StarSpaceWeb/groups/urls.py
from django.urls import path
from . import views

app_name = 'groups'

urlpatterns = [
    path('create',views.CreateGroup.as_view(),name='create'),
    path('',views.ListGroups.as_view(),name='all'),
    path('posts/in/<slug:slug>',views.SingleGroup.as_view(),name='single'),
    path('join/<slug:slug>',views.JoinGroup.as_view(),name='join'),
    path('leave/<slug:slug>',views.LeaveGroup.as_view(),name='leave'),
]

StarSpaceWeb/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('create', views.CreatePost.as_view(), name='create'),
    path('by/<slug:username>', views.UserPosts.as_view(), name='for_user'),
    path('by/<slug:username>/<slug:pk>', views.PostDetail.as_view(), name='single'),
    path('create/comment', views.CreateComment.as_view(), name='create_comment')
]

StarSpaceWeb/groups/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse

from django.contrib.auth import get_user_model
User = get_user_model()

from django import template
register = template.Library()

class Group(models.Model):
    name = models.CharField(max_length=30, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True)
    # description_html = models.TextField(editable=False, blank=True, default='NONE ')
    members = models.ManyToManyField(User, through='GroupMember')

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        # self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('groups:single', kwargs = {'slug':self.slug})

    class Meta:
        ordering = ['name']


class GroupMember(models.Model):
    grp = models.ForeignKey(Group, related_name='membership', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='user_group', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ('grp','user')

StarSpaceWeb/groups/views.py
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.contrib import messages
from django.db import IntegrityError
from django.core.exceptions import ObjectDoesNotExist

from django.views import generic
from groups.models import Group, GroupMember
from . import forms

from django.shortcuts import get_object_or_404

class CreateGroup(generic.CreateView, LoginRequiredMixin):
    model = Group
    fields = ['name', 'description']
    template_name = 'group_form.html'
    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single', kwargs={ 'slug':self.kwargs.get('slug') })


class SingleGroup(generic.DetailView):
    model = Group
    template_name = 'group_detail.html'

class ListGroups(generic.ListView):
    model = Group
    template_name = 'group_list.html'

class JoinGroup(generic.RedirectView, LoginRequiredMixin):

    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single', kwargs={ 'slug':self.kwargs.get('slug') })

    def get(self, *args, **kwargs):
        group = get_object_or_404(Group, slug=self.kwargs.get('slug'))
        try:
            GroupMember.objects.create(user=self.request.user, grp=group)
        except IntegrityError:
            messages.warning(self.request, ('Already a Member !'))
        else:
            messages.success(self.request, ('Now a Member !'))

        return super().get(self.request, *args, **kwargs)

class LeaveGroup(generic.RedirectView, LoginRequiredMixin):

    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single', kwargs={ 'slug':self.kwargs.get('slug') })

    def get(self, *args, **kwargs):
        group = get_object_or_404(Group, slug=self.kwargs.get('slug'))
        try:
            membership = GroupMember.objects.filter(user = self.request.user, grp = group).get()
        except ObjectDoesNotExist:
            messages.warning(self.request, ('Not a Member !'))
        else:
            membership.delete()
            messages.success(self.request, ('Successfully Left the Group !'))

        return super().get(self.request, *args, **kwargs)

StarSpaceWeb/groups/templates/group_base.html
{% extends 'base.html' %}

{% block content %}
<section class="header1 cid-s1BGr2B907" id="header16-19">
    <div class="container">
        <div class="row justify-content-md-left">
            <div class="col-md-10 align-left">
                {% block pre_group %} {% endblock %}
                {% block group_content %} {% endblock %}
                {% block post_group %} {% endblock %}
            </div>
        </div>
    </div>

</section>
{% endblock %}

StarSpaceWeb/groups/templates/group_detail.html
{% extends 'group_base.html' %}

{% block pre_group %}
    <h1>{{ group.name }}</h1>
    <h3>Members: {{ group.members.count }}</h3>
    <p>{{ group.description }}</p>
    {% if user.is_authenticated %}
    <div>
        <a href="{% url 'posts:create' %}" class="btn btn-md btn-black-outline display-4">New Post</a>
        {% if user in group.members.all %}
            <a href="{% url 'groups:leave' slug=group.slug %}" class="btn btn-md btn-black-outline display-4"">Leave</a>
        {% else %}
            <a href="{% url 'groups:join' slug=group.slug %}" class="btn btn-md btn-black-outline display-4"">Join</a>
        {% endif %}
    </div>
    {% endif %}
{% endblock %}

{% block group_content %}
    {% if group.posts.count == 0 %}
        <p>NO POST YET</p>
    {% else %}
        {% for post in group.posts.all %}
            {% include '_post.html' %}
        {% endfor %}
    {% endif %}
{% endblock %}

StarSpaceWeb/groups/templates/group_form.html
{% extends 'group_base.html' %}

{% block group_content %}
    <h3>Create a new group:</h3>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create" class="btn btn-md btn-black-outline display-4">
    </form>
{% endblock %}

StarSpaceWeb/groups/templates/group_list.html
{% extends 'group_base.html' %}

{% block pre_group %}
    {% if user.is_authenticated %}
        <h3>Welcome! <a href="{% url 'posts:for_user' username=user.username %}">@{{user.username}}</a> </h3>
        <a class="btn btn-md btn-black-outline display-4" href="{% url 'groups:create' %}">Create Group</a>
    {% else %}
        <h3>Welcome to Star&Space</h3>
        <a href="{% url 'signup' %}">SignUp</a> for more
    {% endif %}

<p><br></p>
{% endblock %}

{% block group_content %}
    {% for group in object_list %}
        {% if user.is_authenticated %}
            <a href="{% url 'groups:single' slug=group.slug%}"><h5>{{group.name}}</h5></a>
            <p>Members: {{group.members.count}} <br> Posts: {{group.posts.count}}</p>
        {% else %}
            <h5>{{group.name}}</h5>
            <p>Members: {{group.members.count}} <br> Posts: {{group.posts.count}}</p>
        {% endif %}

    {% endfor %}
{% endblock %}