StarSpaceWeb/StarSpaceWeb/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.Index.as_view(), name='home'),
    path('accounts/',include('accounts.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('posts/',include('posts.urls')),
    path('groups/',include('groups.urls')),
]

StarSpaceWeb/groups/urls.py
from django.urls import path
from . import views

app_name = 'groups'

urlpatterns = [
    path('create',views.CreateGroup.as_view(),name='create'),
    path('',views.ListGroups.as_view(),name='all'),
    path('posts/in/<slug:slug>',views.SingleGroup.as_view(),name='single'),
    path('join/<slug:slug>',views.JoinGroup.as_view(),name='join'),
    path('leave/<slug:slug>',views.LeaveGroup.as_view(),name='leave'),
]

StarSpaceWeb/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('create', views.CreatePost.as_view(), name='create'),
    path('by/<slug:username>', views.UserPosts.as_view(), name='for_user'),
    path('by/<slug:username>/<slug:pk>', views.PostDetail.as_view(), name='single'),
    path('create/comment', views.CreateComment.as_view(), name='create_comment')
]

StarSpaceWeb/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Mobirise v4.10.7, mobirise.com">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
  <link rel="shortcut icon" href="{% static "assets/images/logo2.png" %}" type="image/x-icon">
  <meta name="description" content="">

  <title>Stars&Space</title>
  <link rel="stylesheet" href="{% static "assets/web/assets/mobirise-icons/mobirise-icons.css" %}">
  <link rel="stylesheet" href="{% static "assets/tether/tether.min.css" %}">
  <link rel="stylesheet" href="{% static "assets/bootstrap/css/bootstrap.min.css" %}">
  <link rel="stylesheet" href="{% static "assets/bootstrap/css/bootstrap-grid.min.css" %}">
  <link rel="stylesheet" href="{% static "assets/bootstrap/css/bootstrap-reboot.min.css" %}">
  <link rel="stylesheet" href="{% static "assets/dropdown/css/style.css" %}">
  <link rel="stylesheet" href="{% static "assets/socicon/css/styles.css" %}">
  <link rel="stylesheet" href="{% static "assets/theme/css/style.css" %}">
  <link rel="stylesheet" href="{% static "assets/mobirise/css/mbr-additional.css" %}" type="text/css">

    <link rel="stylesheet" href="{% static 'assets/simplesocial/css/master.css' %}">

</head>
<body>
    <section class="menu cid-s36FSkTce5" once="menu" id="menu2-1d">
      <nav class="navbar navbar-expand beta-menu navbar-dropdown align-items-center navbar-fixed-top navbar-toggleable-sm">
          <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <div class="hamburger">
                  <span></span>
                  <span></span>
                  <span></span>
                  <span></span>
              </div>
          </button>
          <div class="menu-logo">
              <div class="navbar-brand">
                  <span class="navbar-logo">
                      <a href="{% url 'home' %}">
                          <img src="{% static 'logoo.png' %}" style="height: 3.8rem;">
                      </a>
                  </span>

              </div>
          </div>
          <div classs="container" id="navbarSupportedContent">
            {% if user.is_authenticated %}
                <ul class="navbar-nav nav-dropdown" data-app-modern-menu="true">
                    <li class="nav-item">
                        <a class="nav-link link text-white display-4" href="{% url 'posts:create' %}">
                            New Post
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link link text-white display-4" href="{% url 'groups:all' %}">
                            Groups
                        </a>
                    </li>
                <div class="navbar-buttons mbr-section-btn">
                    <a class="btn btn-sm btn-primary display-4" href="{% url 'logout' %}">
                        LOG OUT
                    </a>
                </div>
                </ul>

            {% else %}
                <ul class="navbar-nav nav-dropdown" data-app-modern-menu="true">
                    <li class="nav-item">
                        <a class="nav-link link text-white display-4" href="{% url 'groups:all' %}">
                            Groups
                        </a>
                    </li>
                <div class="navbar-buttons mbr-section-btn">
                    <a class="btn btn-sm btn-primary display-4" href="{% url 'login' %}">
                        LOG IN
                    </a>
                </div>
                </ul>
            {% endif %}

        </div>
    </nav>
</section>

<h1> <br> </h1>
<h1> <br> </h1>
<div class="container-jumbotron">
    {% block content %}
    {% endblock %}
</div>


  <script src="{% static "assets/web/assets/jquery/jquery.min.js" %}"></script>
  <script src="{% static "assets/popper/popper.min.js" %}"></script>
  <script src="{% static "assets/tether/tether.min.js" %}"></script>
  <script src="{% static "assets/bootstrap/js/bootstrap.min.js" %}"></script>
  <script src="{% static "assets/smoothscroll/smooth-scroll.js" %}"></script>
  <script src="{% static "assets/dropdown/js/nav-dropdown.js" %}"></script>
  <script src="{% static "assets/dropdown/js/navbar-dropdown.js" %}"></script>
  <script src="{% static "assets/touchswipe/jquery.touch-swipe.min.js" %}"></script>
  <script src="{% static "assets/theme/js/script.js" %}"></script>
  <script src="{% static "assets/starspace/js/master.js"%}" type="text/javascript" ></script>

</body>
</html>

StarSpaceWeb/templates/index.html
{% extends 'base.html' %}

{% block content %}
<section class="header1 cid-s1BGr2B907" id="header16-19">
    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-md-10 align-center">
                <h1 class="mbr-section-title mbr-bold pb-3 mbr-fonts-style display-1">
                    Welcome to Stars & Space
                </h1>

                <p class="mbr-text pb-3 mbr-fonts-style display-5">
                    Register to join the community
                </p>
                <div class="mbr-section-btn"><a class="btn btn-md btn-black-outline display-4" href="{% url 'signup' %}">SIGN UP</a>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="cid-s3sy8X87Ct" id="footer5-1q">
  <div class="container">
      <div class="footer-lower">
          <div class="media-container-row">
              <div class="col-md-12">
                  <hr>
              </div>
          </div>
          <div class="media-container-row mbr-black">
              <div class="col-md-6">
                  <div class="social-list align-center">
                      <p> For contact : </p>
                      <div class="soc-item">
                          <a href="https://www.linkedin.com/in/hardikmehta48/" target="_blank">
                              <span class="socicon-linkedin socicon mbr-iconfont mbr-iconfont-social"></span>
                          </a>
                      </div>
                      <div class="soc-item">
                          <a href="https://github.com/hardikmehta48" target="_blank">
                              <span class="socicon-github socicon mbr-iconfont mbr-iconfont-social"></span>
                          </a>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </div>
</section>

{% endblock %}